### ISSUE TITLE
Forms that have no equivalent in the default language

### ISSUE THREAD

**Issue by chrisprog20** [einpraegsam/powermail#110]
Hi Alex, 

this issue occured in Powermail 3.18.0:
our customer has a multi-language page and publishes forms in German (default language) and French.
Sometimes they only want to put a form on the French version of the page.
Hence they set up the form with language "French" (i.e. it has no equivalent form in default language).

In this case the user gets a message "Spam identifié" and so cannot send the form.
This is because the markers of the fields are emptied if the respective field in the default language is not found in the database.

When I then switch the form's language on "Standard" or "All" - it is working.
But that is not intuitive for the editor. 

Maybe you could elaborate if you include this functionality in your extension.
Thank you for investigating this issue.

**Comment by einpraegsam** [comment]
At the moment every localized form/page/field needs a default version - especially fields. The problem that you described are related to markers, but I think some more properties are note filled because they should be filled from the default language.
There are no plans at the moment to change this behaviour - sorry.

**Comment by chrisprog20** [comment]
Hi Alex, 
thanks for your explanation and your clarification about this topic.
