### ISSUE TITLE
lib.parseFunc_powermail TS overwrites not working

### ISSUE THREAD

**Issue by Skinwalker** [einpraegsam/powermail#128]
TYPO3 8.7.2
Powermail: 3.20.0

---

Tried to add some extra styles to rte links and set forceAbsoluteUrl to 1

Codes like
`lib.parseFunc_powermail.tags.a.typolink.forceAbsoluteUrl = 1`
or
`lib.parseFunc_powermail.tags.a.typolink.ATagsParams = style="color: orange"`

doesn't work - still got the same output in the Object Browser and Frontend.

**Comment by sevenflip** [comment]
Because `lib.parseFunc_powermail` is defined in `ext_typoscript_setup.txt`...

But why is `lib.parseFunc_powermail` and `module.tx_powermail` set inside `ext_typoscript_setup.txt` and not in `Configuration/TypoScript/Main/setup.txt`?
You cannot work without including the main template anyway.

**Comment by einpraegsam** [comment]
There is a Typoscript for Plugin 1 and another for Plugin 2 - both are static templates. In addition there is a Typoscript for the Backend Module together with a configuration that is so important - if it would miss, there where exceptions. That simple

**Comment by sevenflip** [comment]
But the backend module and parseFunc would also work if the config would be inside the main setup, doesn't it?
With the current implementation it's unnecessarily hard to override these settings;
You can only override it by adding an own ext_typoscript_setup.txt

**Comment by einpraegsam** [comment]
What about Pi2?

**Comment by sevenflip** [comment]
Not sure if anyone ever used the Pi2 without also using Pi1? Is that a use-case?

**Comment by einpraegsam** [comment]
I'm not sure. How could I be sure? 
In addition: Backend modules will also break if static template is not included in very first page as far as I know.
Next time: Please think before you criticize free software.

**Comment by sevenflip** [comment]
You can't, because users sometimes have strange use-cases. But you have to be honest, it would be strange if someone tries to use the frontend-view without an existing Pi1-form, because where should the data come from then?
The point with the backend module is totally true.

Next time: I did the "thinking" part, and I was just questioning for your analysis of this case.
And just because it's free doesn't mean that it should not be criticized - I'm always glad for (more or less) useful criticism.

Thanks for understanding this and keep going like you did, because with powermail v3 you did (imho) a great job.
