### ISSUE TITLE
Date with format "d.m.Y" not prefilled in fields with type="date" in Chrome and other Webkitbrowser

### ISSUE THREAD

**Issue by nebrot** [einpraegsam/powermail#202]
We are using GET-Parameters like `tx_powermail_pi1[field][anreisedatum]=01.01.2018` to prefill powermail-fields with type "date" and we don't want the browser-html5-datepicker (bad usability..), so we use "datepicker-force" to use the included lib for every browser. In Webkitbrowser the field isn't prefilled because they want a specific format, see screenshot below. I think the field-value must be set again after changing the input-type to "text" after this line https://github.com/einpraegsam/powermail/blob/develop/Resources/Private/JavaScripts/Powermail/Form.js#L93 : 

`$(this).val($(this).data('date-value'));`

TYPO3: 8.7.8
Powermail: 4.3.0

FF 57: works
IE 11: works
Chrome 62 and Opera 49: don't work

![powermail-bug-date-webkit](https://user-images.githubusercontent.com/6941112/33599265-e590216e-d9a5-11e7-984b-f7ed3dc51b89.png)

**Comment by einpraegsam** [comment]
First of all: You're right. I can also reproduce this issue in chrome.
But the problem is, that the value is lost in JavaScript at the moment when the field is turned from type="date" to type="text". A solution could be to add another data-attribute with the value. And I played a bit with a solution, but it turned out that I would have to use the misc.prefillField() ViewHelper twice, what also needs a refactoring with some caching...
At the end I'm asking myself if it would be easier in your edge case to hardcode the type "text" in the Partial (originally located under EXT:powermail/Resources/Private/Partials/Form/Field/Date.html). What do you think?

**Comment by nebrot** [comment]
Thanks for your quick answer and your workaround with outsourced partial. Do you mean to change this line https://github.com/einpraegsam/powermail/blob/develop/Resources/Private/Partials/Form/Field/Date.html#L10
to `type="text"` ?

Isn't the value already stored in "data-date-value" and could be used to write it again in input-value? I already tried it yesterday and it works in my case.

**Comment by einpraegsam** [comment]
oh ok, I missed that attribute. So you're right. I will deliver a solution asap.

**Comment by einpraegsam** [comment]
I fixed it in the develop branch. Ready for the upcoming release.
Thx for digging into the issue.

**Comment by nebrot** [comment]
Thank you for this fast fix, we'll try it after the release. Keep up the great work!
