### ISSUE TITLE
Use explicit labeling for radio buttons and checkboxes

### ISSUE THREAD

**Issue by slavanga** [einpraegsam/powermail#251]
Both Foundation and Bootstrap recommend to have radio buttons and checkboxes outside of their labels.
This is also required to do any kind of custom styling.

**Implicit labeling in Powermail:**
```html
<label>
  <input type="radio" value="1"> Radio Button
</label>
```

**Explicit labeling in Foundation /  Bootstrap:**
```html
<input type="radio" id="example-radio" value="1">
<label for="example-radio">Radio Button</label>
```

According to [w3.org](https://www.w3.org/WAI/tutorials/forms/labels/#associating-labels-implicitly) explicit labeling is better for accessibility.

> Generally, explicit labels are better supported by assistive technology.

Can we change the markup or add an option to support both cases?

**Comment by einpraegsam** [comment]
You can change the markup in your partials if you don't want that markup. Nevertheless, at the moment I'm going to keep it because it's not a bug and more a "nice to have" for some edge cases.

**Comment by W4ldgeist** [comment]
Changing partials is always a potentially problematic situation, where Viewhelpers change, template structure changes due to some security issue etc. I think it absolutely makes sense to have a core template structure with the most flexible markup possible, so Partial changes only have to happen for functional changes or extensions.
