### ISSUE TITLE
Overwrite RTE.preset for email body?

### ISSUE THREAD

**Issue by Skinwalker** [einpraegsam/powermail#262]
Is it possible to overwrite the RTE.preset for the Sender / Receiver Body Field?
I need to add some custom block styles, which should be only selectable inside the Powermail RTE.

I see that you set the default RTE.preset inside FlexformPi1.xml

```
<settings.flexform.sender.body>
  <TCEforms>
    <config>
      <richtextConfiguration>default</richtextConfiguration>
    </config>
   </TCEforms>
</settings.flexform.sender.body>
```

But i don't find any way to overwrite that ...
Even if I "hardcore" overwrite the richtextConfiguration setting inside FlexformPi1.xml the RTE Config is not applied.

Any ideas?

**Comment by Skinwalker** [comment]
Investigated a little more ...

In tx_news it's possible to overwrite the news bodytext preset via
```
RTE.config.tx_news_domain_model_news.bodytext.preset = minimal
```

Tried this with powermail
```
RTE.config.tx_powermail_domain_model_mail.body.preset = minimal
```
But thats not working

In tx_news the extension fields are set via TCA in powermail via Flexform - maybe thats the problem?

**Comment by Skinwalker** [comment]
Little more research.
Tried to add a new RTE Field to the Flexform

```
tx_powermail.flexForm.addField.settings\.flexform\.receiver\.body2._sheet = receiver
tx_powermail.flexForm.addField.settings\.flexform\.receiver\.body2.label = Body 2
tx_powermail.flexForm.addField.settings\.flexform\.receiver\.body2.config.type = text
tx_powermail.flexForm.addField.settings\.flexform\.receiver\.body2.config.default = Body 2
tx_powermail.flexForm.addField.settings\.flexform\.receiver\.body2.config.enableRichtext = 1
tx_powermail.flexForm.addField.settings\.flexform\.receiver\.body2.config.richtextConfiguration = full
```

I get the new field "Body 2" with the default RTE Settings - so even if I create a new field I can't overwrite richtextConfiguration ...
Is this a problem with powermail or TYPO3? Maybe the richtextConfiguration isn't overwritable?

**Comment by einpraegsam** [comment]
I'm not sure why this behaviour is as it is and I'm also interested in solving this issue. Feel free to add a pull request if you dig more into that problem.

**Comment by tillschweneker** [comment]
@einpraegsam This issue still persists in the latest version. Is there some way to solve this issue?

**Comment by julianhofmann** [comment]
A little more detail on the background:

TYPO3 determines the configuration (or “preset”) of the RTE from a chain of possibilities:
<pre>
$pageTs['preset'] = $pageTs['fieldSpecificPreset'] ?? $tcaFieldConf['richtextConfiguration'] ?? $pageTs['generalPreset'] ?? 'default';
</pre>
(https://github.com/TYPO3-CMS/core/blob/main/Classes/Configuration/Richtext.php#L62)

I.e. the priority is as follows:

1.  if set, take the field-specific configuration from PageTS (`RTE.config.tt_address.description.preset = custom_preset_fancy`)
2.  otherwise, if set, take the field-specific configuration from the TCA (`$GLOBALS['TCA']['tt_address']['columns']['short_profile']['config']['richtextConfiguration'] = 'custom_preset_fancy';`)
3. if still not found, take the generally defined preset from PageTS (`RTE.default.preset = custom_preset_default`)
4. ...and if this does not exist either, use `default`.

This makes the cause clear both here (and of the issue with Powermail, which we could solve in the meantime): as soon as a `richtextConfiguration` is created via TCA, it can *only* be overwritten via field-specific configuration* from PageTS, but *not* via a general change to the preset.

However, it also shows that developers do not need to set a default value in the TCA because TYPO3 may automatically fall back to “default”. Without a field-specific preset via TCA, however, you can set a general value via PageTS.

**Comment by Kaifeck** [comment]
In case going via TCEFORM (as seen in the example) isn't working for someone else, we made it work using RTE:

```
RTE.config {
  tt_content {
    settings\.flexform\.thx\.body.fieldSpecificPreset = my-preset
  }
}
```
