### ISSUE TITLE
Export module: fields not selectable

### ISSUE THREAD

**Issue by uocnma** [einpraegsam/powermail#278]
Hi !

We have encountered the problem that mails cannot be exported to CSV / XLS though the editor sees them by using powermail'S BE-module.
The export file is empty. Expanding the advanced export options there are no blue "bars" which represent the fields of the forms but just yellow bars containing standard fields like IP-address. It seems to me that the form is broken though it was created just approx. three months ago with the same version of powermail as today.
This has happend on our Typo3 7 LTS / powermail 4.4.0

I would like to add some more details but I don't know which ones are relevant. Does anyone know how to fix that or how to debug ?

Kind regards,
Nelson.

**Comment by einpraegsam** [comment]
I can not reproduce this issue on my testsystem with same versions (T3 and powermail). Can you please add a new form on a new page, submit this form in frontend and check if this mail-values can be exported from backend module?

**Comment by uocnma** [comment]
Hi,

I think I solved the problem by myself. The editor wanted to hide the form in the frontend and set a expiration date into the field "stop" of the form-page-element. He should have done that just to the plugin-element.
If you deactivate either the form itself or the form-page - or set an expiration date - the export function behaves as described above. Activating all the elements again restores the export function.

Sorry for bothering you!

Kind regards,
Nelson.

**Comment by sypets** [comment]
Hi, just experienced similar problem. Anyway, found this issue after troubleshooting for nearly an hour. Was very helpful. :thumbsup:

In my case the form had been deactivated. 

This might be a common problem. The problem is that it is relatively rare so it is not well known but may happen.

(Usually if the form should only be available for a timeframe a start/stop is set on the plugin, not on the form. But in this case, the form was deactivated as well).

I would propose to make the visibility of the form irrelevant for the export (e.g. by using only deleted restriction) or put this information in the documentation. 

Problem was reproducible on TYPO3 10.4.14 and powermail 7.4.1 and also latest TYPO3 9 with corresponding latest powermail for that version.
