### ISSUE TITLE
Double Opt-In aktiv

### ISSUE THREAD

**Issue by jensberlin** [einpraegsam/powermail#287]
I need to get the ip and timestamp in englisch with the function "double Opt-In", but it doesn work.
Do you have any idea?

greeting
Jens

**Comment by einpraegsam** [comment]
I don't understand your question. What do you exactly need?

**Comment by jensberlin** [comment]
I try to write it better. Sorry about my english.
Newsletter:
I have a form for german with fields for IP address, e-mail confirmation and login.
In general the IP address is a hidden field. Expanded in the pre-fill field with 1 and variables are {ip}.
The same for e-mail confirmation but variables are timestamp and login are crdate.

Then I created a new page and choose the plugin powermail and included the form. There I am entering receivers and sender.
At settings I choose the option "E-Mail muss bestätigt werden (Double Opt-In)".
In the frontend I send the newsletter login. And it works. In the reciever mail I get ip, timestamp and crdate.

Then I copy the german form for the english translation and send the newsletter login. Now I do not get the ip, timestamp and crdate.

I hope it is more understandable
greeting
Jens

**Comment by einpraegsam** [comment]
There is a known bug in powermail/extbase together with optin-confirmation and language fallback strict. Can you please test another language fallback in your TypoScript configuration?

**Comment by jensberlin** [comment]
Sorry, but we need STRICT. It`s the only solution for us.

Thank you!
greeting
Jens

**Comment by einpraegsam** [comment]
No updates at the moment. 
Sponsoring is welcome of course.

**Comment by dachande** [comment]
After digging into the code it looks like this problem is related to a bug in the TYPO3 core that has been discussed here: https://forge.typo3.org/issues/47192

Although that ticket has been closed there exists a follow up here https://forge.typo3.org/issues/82363

Further investigation revealed that although `$query->getQuerySettings()->setLanguageMode(false);` is used in `MailRepository->findByUid()` to disable any language overlay the `DataMapper` does not respect this setting when retrieving all relations from a `Mail` record especially the relation to the `Answer` records. Therefore the `DataMapper` still uses the language mode set in TypoScript (strict) and forces language overlay which result in 0 `Answer` records returned as all `Mail` records and `Answer` records are created in the default language.

I assume that `Mail` and `Answer` records will and should never be translated, correct? If that's the case, how about creating all `Mail` and `Answer` records with sys_language_uid **-1** instead?
After a little bit of testing, this works as expected with `sys_language_mode = strict` as language overlaying is no longer being done by the `DataMapper`.

**Comment by einpraegsam** [comment]
Yes, the main task is to change language behaviour of mails a answers with sys_language_uid=-1
