### ISSUE TITLE
Sender vs real sender (Receiver mail)

### ISSUE THREAD

**Issue by ursbraem** [einpraegsam/powermail#307]
Please excuse if I'm duplicating something known or even already solved!

In the time of SPF, DKIM etc it's not good practice anymore to send as a random user from a server. 

In Powermail terminology, "sender" is the website visitor who fills in the form, while "receiver" is the website owner (~ or similar). This now leads to confusion between who you want the email to be sent by, and who is the "sender" of the form (the submitter, the filler-inner, the form-user).

If you have a spf record or want to follow best practice, the _sender of the email_ has to be a certain, valid email account from the website owner, eg info@institution.de. This overthrows some well-loved powermail features. 

- In `tx_powermail_domain_model_mail.sender_mail` all you will see is the same official mail address. This concerns the BE module as well. 

- Also, you can't reply to these mails anymore as "receiver", reaching the "sender".

I dare to propose the following changes if `plugin.tx_powermail.settings.receiver.overwrite` is set (or by flag?)

- In `tx_powermail_domain_model_mail.sender_mail` and `tx_powermail_domain_model_mail.sender_name`, log the "submitter"'s data instead of the email sender's data

- Use these values as reply-to for the receiver email

What do you think? 

PS: unrelated, but thanks for the `plugin.tx_powermail.settings.receiver.overwrite.cc` setting – a life saver!

**Comment by einpraegsam** [comment]
The concept behind setting the sender email and name to the website-owner is nowadays outdated. Changing this would be useful but a big task of course.
Nevertheless, hardcoding sendername and email is possible (as you wrote - see https://docs.typo3.org/typo3cms/extensions/powermail/Faq/Index.html#how-to-solve-spf-defiance). Of course powermail also supports the reply-to addresses from the given user import, so the website owner can simply click on reply in his mail-tool.

**Comment by ursbraem** [comment]
I fully understand!

> reply-to addresses from the given user import

https://www.typo3.net/forum/thematik/zeige/thema/119251/
Is that the recommended solution?

**Comment by tillschweneker** [comment]
@einpraegsam 
When I overwrite the the senderName and senderEmail to a valid email address and name of the server sending the mails, I do not have any issues with mail servers following SPF. All mails are received. 

When I don't overwrite the senderName and senderEmail, the mails are flagged as spam (of course).

The issue I'm having with overwriting the senderName and senderEmail is, that one cannot see the sender mail and name in the backend module anymore. 

Is it possible to set the sender_name and sender_email to the values of the form fields marked as email and name? As @ursbraem already proposed?
"In tx_powermail_domain_model_mail.sender_mail and tx_powermail_domain_model_mail.sender_name, log the "submitter"'s data instead of the email sender's data"

**Comment by ursbraem** [comment]
@einpraegsam would you be interested in a PR for this feature? I mean, after all, it's "just" about the list in the BE module, to set an option to display other name / email fields in the list. Or is it? Maybe there are other implications?
