### ISSUE TITLE
systematic Table of TypoScript and TS-options

### ISSUE THREAD

**Issue by DavidBruchmann** [einpraegsam/powermail#311]
A systematic Table of TypoScript and TS-options would be great in the docu.
Currently it's not clear if all available options are used in the setup completely and explanation in the docu is somehow scattered as it's designed with completely different focus.

**Comment by einpraegsam** [comment]
Please look at https://github.com/einpraegsam/powermail/blob/develop/Configuration/TypoScript/Main/setup.txt

It's also copied in https://docs.typo3.org/typo3cms/extensions/powermail/ForAdministrators/BestPractice/MainTypoScript/Index.html

I don't think that we need another table and a third place because this increases the effort on every change.

Thx

**Comment by DavidBruchmann** [comment]
Thanks for the hint, never searched it in BestPractice, I'd move it up on level that it will be found in `.../ForAdministrators/MainTypoScript/Index.html` as it's a reference IMO.
