### ISSUE TITLE
Powermail Submit not working

### ISSUE THREAD

**Issue by unterweltler** [einpraegsam/powermail#341]
**Versions:**
TYPO3 8.7.19
Powermail 6.1.0

---

I included a powermail form on my page and when I try to submit the form nothing happens.
I see the request on
```
http://www.domain.ch/?tx_powermail_pi1%5Baction%5D=create&tx_powermail_pi1%5Bcontroller%5D=Form&cHash=9a0f163e56c045a1d4320e3488adb8f0
```
but it's empty (blank page - no errors)

Tried multiple things, like disabling AJAX Submit, removing complete powermail config, etc. but nothing worked.
I also don't got any JS Errors.

Tried to debug powermail as explained in the FAQ - but the devlog stays empty.

Any ideas?

**Comment by einpraegsam** [comment]
Do you use powermail_cond? If so did you update to the latest version?

**Comment by unterweltler** [comment]
Node - just Powermail

![typo3_extensions](https://user-images.githubusercontent.com/2900602/47082577-53acaa80-d20e-11e8-8475-bc0bba310375.png)

**Comment by unterweltler** [comment]
Ohh boy - found the problem.
I added maintenance index.html inside the TYPO3 Directory - which prevented the Form from submitting. When ich delete it - it works.

Thanks for your help.

**Comment by christophbee** [comment]
**Versions**
TYPO3 10.4.13
Powermail 8.3.1

I am faced with same problem: After submitting a form the request happens but instead of a redirect to the "thank you"-page I see the form again. I checked if it's the same problem like @unterweltler had but that's not the case. 

Are there any other known reasons for this behaviour?
Many thx in advance.
