### ISSUE TITLE
Custom opt-in mail template

### ISSUE THREAD

**Issue by sventendo** [einpraegsam/powermail#356]
Add an option to configure a custom opt-in mail template per form.

Issue originally opened as issue #253 

Fixed in #350

**Comment by mschwemer** [comment]
Dear Sven

thanks for your contribution. This could work technically. 

But I decline the pull request because, the path to the partial is highly integration dependent. The editors do not have any knowledge of the path structure and naming of templates and must not have to do anything with it. If you think of a simple typo in the template, this will break the whole rendering process and the e-mail can not be sent. 

Furthermore, it does not really fit into the concept. If there is the option to change the template for the optin email, there should be also the possibility to choose the template for the receivers and the sender email. 

It is definitly a good idea, but needs more concept.  I will add the idea to the fluid email template issue.
