### ISSUE TITLE
TYPO3 9.5 / Powermail 7: The Page TSConfig setting for filter formSelection doesn't work.

### ISSUE THREAD

**Issue by Bendall234** [einpraegsam/powermail#372]
Could you change the where clause in the function getWhereStatement in file FormSelectorUserFunc.php?

Current behaviour: The select box (forms) shows all forms available in the system.
Expected behaviour: The select box (forms) should respect the storage pid given in the Page TSConfig.

Change from (Line 130):
`$where = 'sys_language_uid IN (-1,0) or (l10n_parent = 0 and sys_language_uid = ' . (int)$language . ')';`

To:
`$where = '(sys_language_uid IN (-1,0) or (l10n_parent = 0 and sys_language_uid = ' . (int)$language . '))';`

Thanks

**Comment by jacques2017** [comment]
Please be careful by changing the where clause.  See issue #375

**Comment by jagodzinski** [comment]
Hi,

it also works if you update following in powermail/Classes/Tca/FormSelectorUserFunc.php

```
/**
     * @param int $startPid
     * @param int $language
     * @return string
     */
    protected function getWhereStatement(int $startPid, int $language): string
    {
        $where = 'sys_language_uid IN (-1,0) or (l10n_parent = 0 and sys_language_uid = ' . (int)$language . ')';
        if (!empty($startPid)) {
            $where .= ' and pid in (' . $this->getPidListFromStartingPoint($startPid) . ')';
        }
        return $where;
    }
```

to

```
/**
     * @param int $startPid
     * @param int $language
     * @return string
     */
    protected function getWhereStatement(int $startPid, int $language): string
    {
        $where = '(sys_language_uid IN (-1,0) or (l10n_parent = 0 and sys_language_uid = ' . (int)$language . '))';
        if (!empty($startPid)) {
            $where .= ' and pid in (' . $this->getPidListFromStartingPoint($startPid) . ')';
        }
        return $where;
    }
```

This is the generated SQL-Query
SELECT * FROM `tx_powermail_domain_model_form` WHERE **(sys_language_uid IN (-1,0) or (l10n_parent = 0 and sys_language_uid = 0) and pid in (457))** AND ((`tx_powermail_domain_model_form`.`deleted` = 0) AND (`tx_powermail_domain_model_form`.`hidden` = 0) AND (`tx_powermail_domain_model_form`.`starttime` <= 1547207700) AND ((`tx_powermail_domain_model_form`.`endtime` = 0) OR (`tx_powermail_domain_model_form`.`endtime` > 1547207700))) ORDER BY `title` ASC LIMIT 10000

The bold part causes that all forms are loaded, because the brackets around sys_language_uid and l10n_parent are missing.

**Comment by einpraegsam** [comment]
Thx to you for your feedback and your analysis. I just pushed a fix to develop branch. Will be published in the next version.
