### ISSUE TITLE
TYPO3 9.5 / Powermail 7: Powermail backend modul export functions doesn't work.

### ISSUE THREAD

**Issue by Bendall234** [einpraegsam/powermail#373]
By default the JQuery-Library is missing.
Even when i load the required JQuery-Library none of the export functions are working.

**Comment by netbrothers-tr** [comment]
I can confirm the problem. @Bendall234, can you confirm that also the action buttons if one mail item are dysfunctional, too?

![mail_list_actions](https://user-images.githubusercontent.com/15143604/50089194-61c67980-0205-11e9-87ee-bf74ddf1f34a.png)

In my case, the only functional button is the edit button (pen icon). I couldn't fix the others by manually including jQuery (#362) in the Backend view script.

What is the underlying problem here?

**Comment by einpraegsam** [comment]
Duplicated to #362

**Comment by einpraegsam** [comment]
Look at #362 
"I just created a fix in develop branch. Can someone pls test it and give me feedback?"
