### ISSUE TITLE
Feature Request: User's Sender E-Mail in the backendmodule

### ISSUE THREAD

**Issue by MFJonesX** [einpraegsam/powermail#396]
Because of the mail-restrictions of the mail servers, we have to overwrite the sender E-Mail via typoscript. Otherwise, the sent e-mail would be blocked by the mail servers because there is no corresponding SPF entry.

However, this makes the backend module pretty unclear because the overwritten e-mail is always used as the sender. It would be nice if the e-mail of the user is still displayed in the backend module.

When creating a form you can specify which field contains the user's e-mail. You could display this e-mail as sender in the BE module instead of the e-mail defined in my typoscript config.

What do you think?

**Comment by einpraegsam** [comment]
In deed in the past it was a feature request to show the really used values for sending mails and I still think that this is the way we want to go. 
We could think about to make the handling to set a different mail for sender a bit nicer in general but there are no plans at the moment.

**Comment by ursbraem** [comment]
@einpraegsam I know we had this already in  #307. 
But we now found an inconsistency that could maybe lead to a fix:

So the issue is about **the BE module in combination with sender override by TS due to SPF**.

```
plugin.tx_powermail.settings.receiver.default.senderName = Name
plugin.tx_powermail.settings.receiver.default.senderEmail = info@domain.ch
plugin.tx_powermail.settings.receiver.overwrite.senderName = Name
plugin.tx_powermail.settings.receiver.overwrite.senderEmail = info@domain.ch
plugin.tx_powermail.settings.sender.default.senderName = Name
plugin.tx_powermail.settings.sender.overwrite.senderEmail = info@domain.ch
```

If the Email to Receiver is not enabled (Subject empty), the BE module looks as expected (varying per user):

![Bildschirmfoto 2019-05-28 um 13 10 56](https://user-images.githubusercontent.com/1446443/58473971-39469200-814a-11e9-8b1a-75633c957142.png)

The email and name values submitted via the form are displayed.

But if the Email to Receiver IS enabled, the BE module falls back to the values that were actually used to send the e-mail (always the same):

![Bildschirmfoto 2019-05-28 um 13 14 57](https://user-images.githubusercontent.com/1446443/58474119-9e9a8300-814a-11e9-9d3f-36a4b410573e.png)

So I have the idea that the solution might be in simply forcing the BE module to behave in the first way always.

**Comment by cepheiVV** [comment]
Our solution to display the "submitted" Name and E-Mail in the Backend Modul is:
https://github.com/cepheiVV/powermail/commit/f06a198fcab531766083d6768b6a356a028751b0

We activate it by TypoScript `module.tx_powermail.settings.list.displaySubmittedReceiverNameAndEmail = 1`

If this is interesting for @einpraegsam to merge, I can optimise this and make a PR.

**Comment by ursbraem** [comment]
@einpraegsam What about this proposal, would you be interested in merging it?
