### ISSUE TITLE
Mail to User do not work

### ISSUE THREAD

**Issue by glucka** [einpraegsam/powermail#401]
Mail to Receiver works correctly but Mail to User not. (over smtp)
The Fields
Sender Name (For Confirmation Mail to User), 
Sender Email (For Confirmation Mail to User),
Subject for Email to Sender (Empty subject disables mail)
filled correctly.

**Comment by einpraegsam** [comment]
I'm pretty sure that this is a configuration issue. Possible problems:
- The editor forget to mark the email field as sender-email-field (checkbox checked in field record?)
- The server blocks to send the email because of a not allowed email address (ask your provider)
- Some TypoScript configuration prevents sending it

**Comment by glucka** [comment]
Thanks Alex!! 
This was the reason: :)
The editor forget to mark the email field as sender-email-field
