### ISSUE TITLE
Field 'marketing_referer_domain' doesn't have a default value

### ISSUE THREAD

**Issue by Teisi** [einpraegsam/powermail#407]
i get following error after submit form if i disable marketing information (basic.disableMarketingInformation = 1).

(Workaround is "basic.disableMarketingInformation = 0")

And no TS for marketing is included.

Error:
"Field 'marketing_referer_domain' doesn't have a default value"

TYPO3 9.5.4
powermail 7.2.0
PHP 7.2.10
mysql 5.7.24

**Comment by einpraegsam** [comment]
Note from Facebook: strict_mode in MySQL could lead to this problem

Question: What and where did you configure exactly to disable marketing information? Did you include the static template for Marketing Information?

**Comment by Teisi** [comment]
if i set "basic.disableMarketingInformation = 0" the form works fine.
This setting is set in BE -> Admin -> Settings -> ExtensionSettings -> powermail

No include of static marketing template.

**Comment by peterkraume** [comment]
Same problem here after switch to MySQL 5.7 with strict mode. `basic.disableMarketingInformation` is disabled in the extension manager. Static marketing template is not included.

The problem is, that in `Configuration/TCA/tx_powermail_domain_model_mail.php` all `marketing_*` fields are unset if `basic.disableMarketingInformation` is true but the fields are still present in the database. Thus the strict mode throws an error because due to the missing TCA there is no default value.

Quick workaround: delete all `marketing_*` fields from table `tx_powermail_domain_model_mail`. Of course this is no permanent solution because the install tool and/or EXT:typo3_console will add the fields again to the database.

The other option is to enable `basic.disableMarketingInformation` but copy the partial template in `Resources/Private/Partials/Misc/MarketingInformation.html` to your own partial directory and set it to an empty value.

**Comment by einpraegsam** [comment]
Thx, merged into develop branch
