### ISSUE TITLE
Attachmenets/E-Mails are not sent to receiver when DOI is enabled

### ISSUE THREAD

**Issue by Geddo** [einpraegsam/powermail#449]
**Setup:**

    "require": { 
      "typo3/cms": "^8.7"      
      "in2code/powermail": "^7.3"
    }
**Test-Form:**
Name, E-Mail, Upload and Submit - nothing special.

**What should be happen:**
- sender (A) and receiver (B) should get the mail-request, also attachments should be visible to the receiver (B)

**What happens:**
- If DOI is enabled the sender (A) receives the confirmation mail with the link and after clicking on the link, sender (A) receives also the confirmation mail. receiver (B) gets NOTHING!
- In both cases the files are uploaded correctly to /uploads/tx_powermail/ also the request is stored in the DB correctly

**Comment by einpraegsam** [comment]
Please give me a hint what you mean with DOI

**Comment by Geddo** [comment]
DOI = DoubleOptIn :-)
PowerMail Option: "Mail must be confirmed (Double Opt-In)"

**Comment by Geddo** [comment]
Dear Alex, did you find some time to figure out what the problem could be?

**Comment by mschwemer** [comment]
Dear @Geddo 

I am currently going through all the old issues and try to reproduce them with the TYPO3 10.4 and branch:develop of powermail. 

I cannot reproduce the mentioned behavior.  After clicking on the confirmation link both e-mails are sent. In the receivers e-mail, there is also the file included as an attachment. 

As TYPO3 V8 ist already ELTS since some time and EXT:powermail version 7.x is not supported any more, I close the ticket. 

If your are still hit by the issue, feel free to re-open it. 

Marcus
