### ISSUE TITLE
Optin and powermail_all marker on localized Forms

### ISSUE THREAD

**Issue by vruescas** [einpraegsam/powermail#451]
We have a very strange behavior with the powermail_all marker when we use Optin on localized Forms. Everything works fine but i recive (receiver mail) the email with the contact form empty, but only on the localized forms, in the original language works propely. I tried with a single marker and not works to. I recive the mail but empty.

Has anybody had this?

best regards, 
Valentin Ruescas

**Comment by epxfrho** [comment]
We have the same issue. When using Opt-In on localized forms, the powermail_all marker is empty in receiver mail and on submit page. In the Opt-In mail itself the powermail_all marker is filled correctly.
And also in the default language everything works fine. 

Typo3 8.7.27, powermail 7.3.1

best wishes
Frank

**Comment by Schweriner** [comment]
There seems to be a nice fix for older versions of powermail: https://github.com/einpraegsam/powermail/issues/213

**Comment by mschwemer** [comment]
Dear @vruescas, @epxfrho, @Schweriner 

I am currently going through all the old issues and try to reproduce them with the TYPO3 10.4 and branch:develop of powermail.

I cannot reproduce the mentioned behavior.

As TYPO3 V8 is already ELTS since some time and EXT:powermail version 7.x is not supported any more, I close the ticket.

If your are still hit by the issue, feel free to re-open it.
