### ISSUE TITLE
Localization of plugins & double opt-in

### ISSUE THREAD

**Issue by instruccionesaldorso** [einpraegsam/powermail#454]
Environment

TYPO3 version(s): 8.7
powermail version: 7.3.1
Is your TYPO3 installation set up with Composer (Composer Mode): yes
OS: Linux

We have 1 form, which we localized into another language.
We have a default powermail plugin using that form, with double opt-in enabled.
We localized that plugin and changed the texts.  

Current Behavior
After submitting the localized form and clicking the link in the e-mail for the double opt-in, the admin e-mail account receives the receiver subject of the default plugin.  

Expected behavior/output
After submitting the localized form and clicking the link in the e-mail for the double opt-in, the admin e-mail account should receive the receiver subject of the localized plugin.

**Comment by mschwemer** [comment]
Dear @instruccionesaldorso 

I am currently going through all the old issues and try to reproduce them with the TYPO3 10.4 and branch:develop of powermail.

I cannot reproduce the mentioned behavior. Each receiver gets the mails in his own language

As TYPO3 V8 is already ELTS since some time and EXT:powermail version 7.x is not supported any more, I close the ticket.

If your are still hit by the issue, feel free to re-open it.
