### ISSUE TITLE
No match with Captcha Extension

### ISSUE THREAD

**Issue by eiranix** [einpraegsam/powermail#65]
TYPO3 7.6.15
Powermail 3.18.0
Captcha 2.0.1

Using powermail with the captcha extension by typoscript:
`plugin.tx_powermail.settings.setup.captcha.use = captcha`

The captcha never matches and gives message:
'Wrong captcha code entered - please try again! '

**Comment by einpraegsam** [comment]
Pls use the latest captcha version 2.0.2

**Comment by eiranix** [comment]
Thank you! Sorry, I thought I had the latest...

**Comment by raffisdj** [comment]
Hi there.
I am using typo3 7.6.16 and powermail 2.25.4 for our customer and we do not have a chance to easily update powermail on version 3.x.
Is there any chance / version of the regular "captcha" extension so that it can be properly used with powermail 2.x?
With the latest "captcha" version 2.0.2, I constantly get a mismatch ("wrong code") when trying to submit the form.

**Comment by einpraegsam** [comment]
I have no idea which version of captcha works with version 2.x of powermail.
Pls test by yourself or simply switch to a calculating captcha or even better just remove any kind of captchas because of some reasons.
BTW: There is no support of powermail 2.x any more

**Comment by raffisdj** [comment]
Thanks, just tested all versions of captcha, no compatibility here.
As we have some long-term systems that have quite complex and customized powermail solutions and as in such a case, a powermail-update is not that easy to implement, I'll check your hint here (https://www.typo3.net/forum/thematik/zeige/thema/125617/) or look for an alternative.
Thanks
