### ISSUE TITLE
Ignored Submit Page with Double Opt-In on

### ISSUE THREAD

**Issue by malbezem** [einpraegsam/powermail#690]
Hello,

With the Opt-In feature turned on, Redirecting to any other Pager after submit is not working.
I turned the feature off and it worked just fine. 

It seems that the Opt-In feature is forcing the optin_seeMail Message to show.
What I want instead, is that the form redirect to a specific Page after the submit event.

Thanks

**Comment by mschwemer** [comment]
Hi,

this is correct and an intended behavior. Why?

Because the submit step is meant to be the final confirmation of the form submission. If you want a double opt-in, the form is not finally confirmed and this not submitted.

If you want to achieve this, you can modify the template `Resources/Private/Templates/Form/Create.html` and replace the translate viewhelper with the intended content or forward the request from there.

**Comment by malbezem** [comment]
There should be a redirect page after the first and final submission. This way I have to change the Extension code that can be easily overwritten when the extension is updated.

**Comment by fgerards** [comment]
ofc there should be the possibility to redirect to another page after the first-step form of a double optin is submitted. There is no reason why you disable the RedirectFinisher-redirectToUri method intentionally without teling at least the editor, that anything he fills into the "settings.flexform.thx.redirect" field is useless if optin is active. This is very bad user communication and leads to sufficient confusion on both developer and editor side. Please correct that.
