### ISSUE TITLE
Form submit: Scroll down to form anchor

### ISSUE THREAD

**Issue by cweiske** [einpraegsam/powermail#72]
I've got a form on the bottom of a page. When submitting the form, the "is this correct" page is shown - but scrolled to the top. The user has to scroll all the way down to the form again to see this.

Powermail should add an anchor to the form action, so that the browser automatically scrolls down. TYPO3 automatically generates content ID anchors (`id="c123"`) so they could be used.

**Comment by einpraegsam** [comment]
You can add a section to the form viewhelper if you want. 
Nevertheless, If I don't want to "scroll away" on submit, I simply activate AJAX submit. Example on http://powermail.in2code.ws/index.php?id=9

**Comment by Kitzberger** [comment]
Because the ttContentData array is empty (I assume due to calling initializeObject() twice?) when returning to the formAction after unsuccessfully (due to the serverside validation errors) trying to submit we cannot rely on the content uid for the Form.html.

As a workaround we added a section parameter to the Templates/Form/Form.html:
```
section="powermail-form-{form.uid}"
```
and a id attribute to the Layouts/Default.html:
```
<div class="tx-powermail" id="powermail-form-{f:if(condition:form.uid,then:form.uid,else:mail.form.uid)}">
	<f:render section="main" />
</div>
```
That did the trick for us.

As a side note: the Confirmation.html actually uses that content uid as section parameter when hitting "back to form".
