### ISSUE TITLE
Increasing number of false positives for spam (honey pot)

### ISSUE THREAD

**Issue by sypets** [einpraegsam/powermail#824]
Recently, the number of emails detected as spam via honey pot which were not spam has increased. I have setup a spam log and notification via email and this very rarely sends anything. But recently, there have been several emails for spam blocked, all related to honey pot. The fields which were displayed in the mail were very un-spam-like. I also contacted the people and got confirmed that it was a legitimate request.

By default, honey pot check has an indicator of 5 which will result in spamfactor of 80%, so if only the honey pot fails, it will be considered spam above threshold of 75%. This means, for this answer, there will be no email sent and no entry recorded.

I can change the configuration to give "honey pot" a lower indicator or set the threshold higher.

However, the question is why this might fail. I can still contact the people to ask for specifics but I am not sure what to ask for. I have found one PR related to honey pot with screen readers #478.

**Comment by einpraegsam** [comment]
Hello,

thx for the insights to the spam behaviour. We initially used a higher value for honey pot failures because this indication seems to be very clear for us.
Nevertheless technique changes from time to time. So we had a bigger autocomplete issue of chrome in the past that we've fixed. Maybe browsers changed there function again...

**Comment by einpraegsam** [comment]
Change merged
