### ISSUE TITLE
Style error message differently? (without bullet marker)

### ISSUE THREAD

**Issue by sypets** [einpraegsam/powermail#834]
I used "introduction" package with bootstrap_package on TYPO3 v11 with powermail 10.2.0.

The static include "Add classes and CSS based on bootstrap (powermail)" was included.

The error message looks nice except for the bullet.

![image](https://user-images.githubusercontent.com/13206455/202103578-c4efb5b9-5c61-4f9a-a732-cac02d36c9cc.png)

```
<ul class="powermail_message powermail_message_error">
   <li>Spam recognized: 50% Spam chance in this message!</li>
</ul>
```

**Comment by einpraegsam** [comment]
I never installed bootstrap_package, so maybe this problem is related to this extension.

Default CSS should look like:
![Screenshot 2022-11-16 at 10-59-02 Powermail for TYPO3 11 active (Mail Notify)](https://user-images.githubusercontent.com/89055/202149624-9412947c-af67-40e2-b78a-8b32a6d815ec.png)
