### ISSUE TITLE
PHP Error: Undefined array key 1 for Captcha

### ISSUE THREAD

**Issue by contini** [einpraegsam/powermail#863]
If the php version is set to 8 or 8.1 an error occurs if the form contains a captcha. Instead of the captcha this error is displayed:
PHP Warning: Undefined array key 1 in .../typo3conf/ext/powermail/Classes/Domain/Service/CalculatingCaptchaService.php line 192
I am using typo3 11.5.23 and powermail 10.7.0. If I switch back to php 7.4 the error is gone. Nearly the same setting at a different Hoster does not produce the error (only difference being typo3 11.5.21).

**Comment by einpraegsam** [comment]
Maybe this problem is related to a missing or a wrong TypoScript definition. Default settings (constants) `textAngle = -5,5` are splitted at the comma. So there should be 2 values. I could fix this issue in line 192, but I'm pretty sure that also line 202, 213, and maybe some others should also be fixed.
Can you pls check with TypoScript object browser on the page where the plugin is stored, if there is a value for textAngle (like in my screenshot). Don't forget to switch from constants to setup (This is a problem I keep stumbling over myself).
![Screenshot 2023-03-01 at 17-45-37 TypoScript Object Browser · ShortForm · New TYPO3 site TYPO3 CMS 11 5 22](https://user-images.githubusercontent.com/89055/222205919-df682977-a39b-4d80-860e-8534b082e12f.png)

**Comment by contini** [comment]
Spot on! I had set one value with a single digit. Changing that, everything works fine!
Thanks for pointing that out.

**Comment by einpraegsam** [comment]
Thx for the final feedback
